<<<<<<< HEAD
export const actionTypes = {
    SET_PRODUCTS: "SET_PRODUCTS",
    SELECTED_PRODUCTS: 'SELECTED_PRODUCT',
    REMOVE_SELECTED_PRODUCTS: 'REMOVE_SELECTED_PRODUCT'
=======
export const actionTypes = {
    SET_PRODUCTS: "SET_PRODUCTS",
    SELECTED_PRODUCTS: 'SELECTED_PRODUCT',
    REMOVE_SELECTED_PRODUCTS: 'REMOVE_SELECTED_PRODUCT'
>>>>>>> 9c553b61de21c417676afb8a054a76c222dbb73e
}