<<<<<<< HEAD
export const ActionTypes = {
    SET_PRODUCTS: 'SET_PRODUCTS',
    SELECTED_PRODUCTS: 'SELECTED_PRODUCTS',
    REMOVE_SELECTED_PRODUCTS: 'REMOVE_SELECTED_PRODUCTS'
}
=======
export const ActionTypes = {
    SET_PRODUCTS: 'SET_PRODUCTS',
    SELECTED_PRODUCTS: 'SELECTED_PRODUCTS',
    REMOVE_SELECTED_PRODUCTS: 'REMOVE_SELECTED_PRODUCTS'
}
>>>>>>> 9c553b61de21c417676afb8a054a76c222dbb73e
